<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PartnerService" targetNamespace="http://www.example.com/camunda/service"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://www.example.com/camunda/service"
                  xmlns:ns1="http://www.example.com/camunda/types" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	TYPE DEFINITION
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://www.example.com/camunda/types" schemaLocation="../schema/types.xsd"/>
    </schema>
  </wsdl:types>
  
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	MESSAGE TYPE DEFINITION - Definition of the message types used as 
	part of the port type defintions
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <wsdl:message name="getPartnerRequestMessage">
    <wsdl:part name="payload" element="ns1:getPartner"/>
  </wsdl:message>
  <wsdl:message name="getPartnerResponseMessage">
    <wsdl:part name="payload" element="ns1:getPartnerResponse"/>
  </wsdl:message>
  
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	PORT TYPE DEFINITION - A port type groups a set of operations into
	a logical service unit.
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <wsdl:portType name="PartnerServicePortType">
    <wsdl:operation name="getPartner">
      <wsdl:input message="client:getPartnerRequestMessage"/>
      <wsdl:output message="client:getPartnerResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	BINDING DEFINITION
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <wsdl:binding name="PartnerServiceSoapBinding" type="client:PartnerServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getPartner">
      <soap:operation style="document" soapAction="http://www.example.com/camunda/service/getPartner"/>
      <wsdl:input>
        <soap:body use="literal" parts="payload"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="payload"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	SERVICE DEFINITION
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <wsdl:service name="PartnerService">
    <wsdl:port name="PartnerServicePortTypePort" binding="client:PartnerServiceSoapBinding">
      <soap:address location="http://localhost:8088/partnerService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
